import{S as L,a as b,i as d}from"./assets/vendor-MjawMu3A.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const w=document.querySelector(".search-form"),i=document.querySelector(".gallery"),m=document.querySelector(".search-loader"),l=document.querySelector(".load-more"),p=document.querySelector(".load-more-loader");let u=!1,a=1,h="",f=0;const g=40,E="53768760-b5f65296e9b3085f39f459f54",v=800,S=new L(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});w.addEventListener("submit",q);l.addEventListener("click",P);function q(n){n.preventDefault();const o=n.target.elements.query.value.trim();o&&(h=o,a=1,f=0,u=!1,i.innerHTML="",l.classList.add("is-hidden"),m.classList.remove("is-hidden"),y())}function P(){u=!0,l.classList.add("is-hidden"),p.classList.remove("is-hidden"),a+=1,y()}async function y(){const n=Date.now();let o=null,t=!1;try{const s=await b.get("https://pixabay.com/api/",{params:{key:E,q:h,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:g}}),{hits:e,totalHits:r}=s.data;f=r,e.length===0&&a===1?d.warning({message:"Sorry, there are no images matching your search query.",position:"topRight",backgroundColor:"#EF4040",color:"#FFBEBE",messageColor:"#FAFAFB",icon:"fa fa-times-circle",iconColor:"rgba(250, 250, 251, 1)",timeout:5e3}):o=e}catch(s){t=!0,d.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(s)}finally{const s=Date.now()-n,e=Math.max(0,v-s);setTimeout(()=>{m.classList.add("is-hidden"),p.classList.add("is-hidden"),o&&!t&&M(o)},e)}}function M(n){const o=n.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b><span>${t.likes}</span></p>
          <p><b>Views</b><span>${t.views}</span></p>
          <p><b>Comments</b><span>${t.comments}</span></p>
          <p><b>Downloads</b><span>${t.downloads}</span></p>
        </div>
      </li>
    `).join("");i.insertAdjacentHTML("beforeend",o),R().then(()=>{if(S.refresh(),u){const t=i.firstElementChild;if(!t)return;const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}a*g<f?l.classList.remove("is-hidden"):d.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"})})}function R(){const n=i.querySelectorAll("img");return Promise.all([...n].map(o=>new Promise(t=>{o.complete?t():(o.addEventListener("load",t),o.addEventListener("error",t))})))}
//# sourceMappingURL=index.js.map
